#SC MAKE BY SENAYEL ISLAM DIP
#CRADIT BY DIP ISLAM
#---------------------------import----------------------------#
import os
import random
import sys
import time
#---------------------------COLOR----------------------------#
bblack="\033[1;30m"         # Black
M="\033[1;31m"            # Red
H="\033[1;32m"         # Green
y="\033[1;33m"        # Yellow
b="\033[1;34m"          # Blue
P="\033[1;35m"        # Purple
C="\033[1;36m"          # Cyan
B="\033[1;37m"         # White
my_color = [
 b,C,P,H,M,y]
rndm = random.choice(my_color)
#---------------------------RANDOM GF----------------------------#
q="https://www.facebook.com/profile.php?id=100091496148948"
w="https://www.facebook.com/profile.php?id=100091797902610"
e="https://www.facebook.com/profile.php?id=100089256112071"
r="https://www.facebook.com/profile.php?id=100092180919697"
t="https://www.facebook.com/mstshamima.akter.585"
p="https://www.facebook.com/profile.php?id=100088137867614"
y="https://www.facebook.com/profile.php?id=100091247164005"
u="https://www.facebook.com/muhua.islam.9"
i="https://www.facebook.com/profile.php?id=100052675703946"
o="https://www.facebook.com/profile.php?id=100000386112466"
k="Tomar Kopale Gf Nai 🤣 "
z="Gf Lagbo Na Hat Mere Ghumai Jao😆 "
x="Tomar Prem Korar Boyos Hoy Nai Babu🤭 "
v="Valobasa Dhoner Ball..! Mone Khali Chudar Tal😁 "
gf=[q,w,e,r,t,y,u,i,o,k,z,x,v]
rdm=random.choice(gf)
#---------------------------DEF----------------------------#
def clr():
	os.system('clear')
#---------------------------DEF LINE----------------------------#
def line():
	print(f"╔═════════════════════════════════════╗")
#---------------------------DEF LINE-2---------------------------#
def line2():
	print(f"╚═════════════════════════════════════╝")
#---------------------------DEF LINE-3---------------------------#
def line3():
	print(f"\033[1;32m══════════════════════════════════════════════════════════════════════════════")
#---------------------------RANDOM BF----------------------------#
q="https://www.facebook.com/profile.php?id=100052191981257"
w="https://www.facebook.com/profile.php?id=100077855090738"
e="https://www.facebook.com/profile.php?id=100094956533819"
r="https://www.facebook.com/profile.php?id=100054640493605"
t="https://www.facebook.com/profile.php?id=100094151988033"
p="https://www.facebook.com/profile.php?id=100000251313982"
y="https://www.facebook.com/profile.php?id=100090374813862"
u="https://www.facebook.com/profile.php?id=100076343509343"
i="https://www.facebook.com/profile.php?id=100080250987143"
o="https://www.facebook.com/zozo.vi.7?mibextid=9R9pXO"
k="Tomar Kopale Bf Nai 🤣 "
z="Gf Lagbo Na Hat Mere Ghumai Jao😆 "
x="Tomar Prem Korar Boyos Hoy Nai Babu🤭 "
v="Valobasa Dhoner Ball..! Mone Khali Chudar Tal😁 "
gf=[q,w,e,r,t,y,u,i,o,k,z,x,v]
bdm=random.choice(gf)
#---------------------------DEF---------------------#
def blr():
	os.system('clear')
#---------------------------LOGO----------------------------#
os.system('clear')
logo=(f"""
\033[1;32m ######   ########        ########  ######## 
\033[1;32m##    ##  ##         ##   ##     ## ##       
\033[1;32m##        ##         ##   ##     ## ##       
\033[1;32m##   #### ######   ###### ########  ######   
\033[1;32m##    ##  ##         ##   ##     ## ##       
\033[1;32m##    ##  ##         ##   ##     ## ##       
\033[1;32m ######   ##              ########  ##       

\033[1;32m╔═════════════════════════════════════════════╗
\033[1;32m║  \033[1;33m[<×>] CREATED BY   :  \033[1;33mSENAYEL ISLAM  DIP   \033[1;32m║
\033[1;32m║  \033[1;32m[<×>] ON FACEBOK   :  \033[1;32mSENAYEL ISLAM        \033[1;32m║
\033[1;32m║  \033[1;35m[<×>] ON GITHUB    : \033[1;35m《DIP123452》         \033[1;32m║
\033[1;32m║  \033[1;36m[<×>] TOOL STATUS  :  \033[1;36mGF+BF                \033[1;32m║
\033[1;32m╚═════════════════════════════════════════════╝
\033[1;32m [+] PLEASE SUPPORT ME.......	       \033[1;32m║
\033[1;32m [+] WELCOME TO MY TOOL.........       \033[1;32m║
\033[1;32m ══════════════════════════════════════╝
""")
#---------------------------SYSTEM----------------------------#
for i in logo:
	sys.stdout.write(i)
	sys.stdout.flush()
	time.sleep(0.005)
def DIP():
	line()
	print(f"\033[1;32m║[1] I NEED GF	                      \033[1;32m║")
	print(f"\033[1;32m║[2] I NEED BF		 	      \033[1;32m║")
	print(f"\033[1;32m║[3] MY FACEBOOK ID	 	      \033[1;32m║")
	print(f"\033[1;32m║[4] MESSENGER CHAT GROUP   	      \033[1;32m║")
	print (f"\033[1;32m║[0] TARMINAL EXIT	              \033[1;32m║")
	line2()
	DIP =input(f"\n[√] CHOOSE : {M}")
	if DIP in ["1"," 01"]:
		GF()
	if DIP in ["2","02"]:
		BF()
	if DIP in ["3","03"]:
		FA()
	if DIP in ["4","04"]:
		ME()
	if DIP in ["0","00"]:
		exit()
		clr()
		blr
	else:
		exit()
		
#---------------------------BEF GF----------------------------#
clr()
print(logo)
def GF():
	print("\033[1;32mLOADING.......")
	time.sleep(1.5)
	clr()
	print(logo)
	print(f"SEARCH YOUE GF ID LINK : {M}{rdm}{rndm}")
	line3()
	input(' \033[1;32mPRESS ENTER TO BACK   : ')
	os.system('clear')
	print(logo)
	DIP()
#---------------------------BEF BF----------------------------#
blr()
print(logo)
def BF():
	print("\033[1;32mLOADING.......")
	time.sleep(1.5)
	blr()
	print(logo)
	print(f"SEARCH YOUE BF ID LINK : {M}{bdm}{rndm}")
	line3()
	input(' \033[1;32mPRESS ENTER TO BACK   : ')
	os.system('clear')
	print(logo)
	DIP()
#---------------------------BEF FA----------------------------#
def FA():
	os.system("xdg-open https://www.facebook.com/profile.php?id=100077855090738")
	os.system('clear')
	print(logo)
	DIP()
#---------------------------BEF ME----------------------------#
def ME():
	os.system("xdg-open https://m.me/j/Aba9q5R2NNswNscj/")
	os.system('clear')
	print(logo)
	DIP()
#---------------------------END----------------------------#
DIP()
